spring:
  datasource:
    url: jdbc:mysql://${DBHOST:localhost}:${DBPORT:3306}/${DBNAME:genericupload}?useUnicode=true&characterEncoding=utf8&useSSL=${USE_SSL:false}
    username: ${DBUSER:root}
    password: ${DBPASSWORD:}
  jpa:
    show-sql: false

flyway:
  password: ${DBPASSWORD:}
  schemas: ${DBNAME:genericupload}

kc:
  realm: ${KC_REALM}
  master.realm: ${KC_MASTER_REALM}
  client.id: ${KC_CLIENT_ID}
  server.url: ${KC_SERVER_URL}
  username: ${KC_USERNAME}
  password: ${KC_PASSWORD}
  timeout: ${KC_TIMEOUT}

logging:
  file: ${LOG_DIR:${HOME}}/generic-upload.log

deadletterDirectory: ${DEADLETER_DIR:/tmp/deadletter}

application:

aws.s3.bucket: generic-upload-tis-team-local
