spring:
  datasource:
    url: jdbc:mysql://${DBHOST}:${DBPORT}/${DBNAME}?useUnicode=true&characterEncoding=utf8&useSSL=${USE_SSL}
    username: ${DBUSER}
    password: ${DBPASSWORD}

flyway:
  password: ${DBPASSWORD}
  schemas: ${DBNAME}

kc:
  realm: ${KC_REALM}
  master.realm: ${KC_MASTER_REALM}
  client.id: ${KC_CLIENT_ID}
  server.url: ${KC_SERVER_URL}
  username: ${KC_USERNAME}
  password: ${KC_PASSWORD}
  timeout: ${KC_TIMEOUT}

logging:
  file: ${LOG_DIR}/generic-upload.log

# ===================================================================
# Azure block blob storage properties
# ===================================================================
azure:
  accountName: ${CLOUD_BLOB_ACCOUNT_NAME}
  accountKey: ${CLOUD_BLOB_ACCOUNT_KEY}
  containerName: ${CLOUD_BLOB_CONTAINER_NAME}
  servicebus:
    connection-string: ${SERVICE_BUS_CONNECTION_STRING}
    queue-name: ${SERVICE_BUS_QUEUE_NAME}
    queue-receive-mode: ${SERVICE_BUS_Q_RECEIVE_MODE}
    topic-name: ${SERVICE_BUS_TOPIC_NAME}
    subscription-name: ${SERVICE_BUS_SUBSCRIPTION_NAME}
    subscription-receive-mode: ${SERVICE_BUS_S_RECEIVE_MODE}

deadletterDirectory: ${DEADLETER_DIR}