package com.transformuk.hee.tis.genericupload.service.parser;

public class AssessmentHeaderMapper extends ColumnMapper {
  public AssessmentHeaderMapper() {
    fieldNameSource = new String[]{
            "surname",
            "gmcNumber",
            "gdcNumber",
            "publicHealthNumber",
            "type",
            "status",
            "programmeName",
            "programmeNumber",
            "reviewDate",
            "curriculumName",
            "portfolioReviewDate",
            "daysOutOfTraining",
            "periodCoveredFrom",
            "periodCoveredTo",
            "monthsCountedToTraining",
            "pya",
            "outcome",
            "underAppeal",
            "outcomeNotAssessed",
            "outcomeNotAssessedOther",
            "academicOutcome",
            "externalTrainer",
            "nextRotationGradeName",
            "traineeNotifiedOfOutcome",
            "nextReviewDate",
            "comments",
            "tenPercentAudit",
            "detailedReasons",
            "mitigatingCircumstances",
            "competencesToBeDeveloped",
            "otherRecommendedActions",
            "recommendedAdditionalTrainingTime",
            "additionalCommentsFromPanel",
            "knownConcerns",
            "concernSummary",
            "responsibleOfficerComments"
    };

    fieldNameTarget = new String[]{
            "Trainee Surname*",
            "GMC Number",
            "GDC Number",
            "Public Health Number",
            "Type",
            "Status",
            "Programme name*",
            "Programme number*",
            "Review date*",
            "Curriculum name*",
            "Portfolio review date",
            "Days out of training",
            "Period covered from",
            "Period covered to",
            "Months OOPR/OOPT counted towards training",
            "PYA",
            "Outcome",
            "Under appeal",
            "Unsatisfactory Outcome/Not Assessed Reason",
            "Unsatisfactory Outcome/Not Assessed Reason (Other)",
            "Academic Outcome",
            "External trainer",
            "Grade at next rotation",
            "Trainee notified of outcome",
            "Next review date",
            "Comments",
            "10% audit - lay member",
            "Detailed reason",
            "Mitigating circumstances",
            "Competences which need to be developed by next ARCP",
            "Other recommended actions",
            "Recommended additional training time (if required)",
            "Additional comments from the panel",
            "Known concerns",
            "Concern summary",
            "Responsible officer comments"

    };
  }
}
